const data = {
  products: [
    {
      name: 'Camiseta SpaceX Crew 5',
      slug: 'spacex-crew-shirt',
      category: 'Camisetas',
      image: 'images/p1.jpg',
      price: 120.0,
      countInStock: 10,
      brand: 'SpaceX',
      rating: 4,
      numReviews: 10,
      description: 'Camiseta de algodon manga corta logotipo de SpaceX Crew',
    },
    {
      name: 'Gorra SpaceX Flacon Heavy - Fitted',
      slug: 'spacex-crew-shit',
      category: 'Camisetas',
      image: 'images/p1.jpg',
      price: 120.0,
      countInStock: 10,
      brand: 'SpaceX',
      rating: 4,
      numReviews: 10,
      description: 'Camiseta de algodon manga corta logotipo de SpaceX Crew',
    },
    {
      name: 'Camiseta SpaceX Crew 5',
      slug: 'spacex-crew-shit',
      category: 'Camisetas',
      image: 'images/p1.jpg',
      price: 120.0,
      countInStock: 10,
      brand: 'SpaceX',
      rating: 4,
      numReviews: 10,
      description: 'Camiseta de algodon manga corta logotipo de SpaceX Crew',
    },
  ],
};
