const data = {
  products: [
    {
      name: 'Camiseta SpaceX Crew 5',
      slug: 'spacex-crew-shirt',
      category: 'Camisetas',
      image: 'images/p1.jpeg',
      price: 120000,
      countInStock: 10,
      brand: 'SpaceX',
      rating: 4,
      numReviews: 10,
      description: 'Camiseta de algodon manga corta logotipo de SpaceX Crew',
    },
    {
      name: 'Gorra SpaceX Flacon Heavy - Fitted',
      slug: 'spacex-falcon-cap',
      category: 'Gorras',
      image: 'images/p2.jpeg',
      price: 39000,
      countInStock: 10,
      brand: 'SpaceX',
      rating: 4,
      numReviews: 10,
      description: 'Gorra con logo SpaceX Flancon Heavy',
    },
    {
      name: 'Rover Lunar Apollo - Steel Model Kit',
      slug: 'rover-lunar-apollo',
      category: 'Juguetes',
      image: 'images/p3.jpeg',
      price: 16000,
      countInStock: 5,
      brand: 'Apollo',
      rating: 5,
      numReviews: 3,
      description: 'Figura en metal del Rover de la misión Lunar Apollo ',
    },
    {
      name: 'Minimochila Loungefly Shuttle',
      slug: 'minibackpack-loungefly-shuttle',
      category: 'Bolsos y Maletas',
      image: 'images/p4.jpeg',
      price: 85000,
      countInStock: 3,
      brand: 'Lougefly',
      rating: 5,
      numReviews: 3,
      description: 'Figura en metal del Rover de la misión Lunar Apollo ',
    },
  ],
};

export default data;
